name: Docker Image CI

on:
  push:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image (dev)
        if: endsWith(github.ref, '/dev')
        run: docker build . --file Dockerfile --tag bitsler/ton-wallet:$(cat VERSION)-dev

      - name: Build the Docker image (main)
        if: endsWith(github.ref, '/main')
        run: docker build . --file Dockerfile --tag bitsler/ton-wallet:$(cat VERSION) --tag bitsler/ton-wallet:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_TOKEN }}

      - name: Push image (dev)
        if: endsWith(github.ref, '/dev')
        run: |
          docker push bitsler/ton-wallet:$(cat VERSION)-dev

      - name: Push image (main)
        if: endsWith(github.ref, '/main')
        run: |
          docker push bitsler/ton-wallet:$(cat VERSION)
          docker push bitsler/ton-wallet:latest
